version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - cassandra
    volumes:
      - ./flask:/app  # Ensure local code directory is mounted correctly
    networks:
      - cassandra_net
    restart: always

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=256M"
    networks:
      - cassandra_net

  cassandra2:
    image: cassandra:4.1
    container_name: cassandra2
    depends_on:
      - cassandra
    environment:
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=256M"
    ports:
      - "9043:9042"
    networks:
      - cassandra_net

networks:
  cassandra_net:
    driver: bridge
